classDiagram
direction TB
    class Personaggio {
	    -String nome
	    -int salute
	    -int fame
	    -int sete
	    +bevi()
	    +mangia()
	    +abilitàSpeciale()
	    +perdiVita()
	    +recuperaVita()
    }

    class Oggetti {
	    -String nome
	    -String effetto
	    +usa()
    }

    class SelezionePersonaggio {
	    +MostraPersonaggiDisponibili()
    }

    class Gestore {
	    -int n_Turno
	    -int punteggio
	    +generaIncontro(Incontro incontro)
	    +aggiungiPunteggio()
	    +rimuoviPunteggio()
    }

    class Enemy {
	    -String nome
	    -int salute
	    -int danno
	    +attack()
    }

    class Incontro {
	    -String tipoIncontro
	    +interagisci(Personaggio p)
    }

    class Grafica {
	    +mostraPersonaggioScelto(Personaggio personaggio)
    }

    Gestore ..> Personaggio
    Gestore ..> Grafica
    SelezionePersonaggio "1" --> "1" Personaggio
    Enemy --|> Incontro
    Oggetti --|> Incontro
    Gestore ..> Incontro