/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettogdr;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

/**
 *
 * @author arcaleni.daniele2
 */
public class Grafica extends javax.swing.JFrame {
    private JPanel selezionato = null;
    private String player = "";
    Enemy nemico = new Enemy("PrimoNemico", 100, "NomeOgettoPerso",20);

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        initComponents();
        BottoneSceltaPersonaggio.setEnabled(false);
        BottoneSceltaPersonaggio.setText("Gioca");
        setTitle("Selezione Personaggio");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(640, 480);
        setLocationRelativeTo(null);
        /*PanelScegliPersonaggio.setVisible(false);*/
        PanelInizioPartita.setVisible(false);
        txtOggettoPerso.setVisible(false);

        PanelPersonaggio1.setLayout(new BorderLayout());
        JLabel label1 = creaLabel("/progettogdr/PersonaggioGDR.png", 90, 120);
        PanelPersonaggio1.add(label1, BorderLayout.CENTER);
        PanelPersonaggio1.setBounds(25, 90, 150, 200);
        PanelScegliPersonaggio.add(PanelPersonaggio1);

        PanelPersonaggio2.setLayout(new BorderLayout());
        JLabel label2 = creaLabel("/progettogdr/secondoPersonaggioGDR.png", 90, 120);
        PanelPersonaggio2.add(label2, BorderLayout.CENTER);
        PanelPersonaggio2.setBounds(230, 90, 160, 200);
        PanelScegliPersonaggio.add(PanelPersonaggio2);

        PanelPersonaggio3.setLayout(new BorderLayout());
        JLabel label3 = creaLabel("/progettogdr/TerzoPersonaggioGDR.png", 90, 120);
        PanelPersonaggio3.add(label3, BorderLayout.CENTER);
        PanelPersonaggio3.setBounds(463, 90, 140, 200);
        PanelScegliPersonaggio.add(PanelPersonaggio3);

        MouseAdapter selezioneListener = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e){
                selezionato = (JPanel) e.getSource();

                if (selezionato == PanelPersonaggio1){
                    player = "/progettogdr/PersonaggioGDR.png";
                }
                else if (selezionato == PanelPersonaggio2){
                    player = "/progettogdr/secondoPersonaggioGDR.png";
                }
                else if (selezionato == PanelPersonaggio3){
                    player = "/progettogdr/TerzoPersonaggioGDR.png";
                }

                evidenziaSelezione();
                BottoneSceltaPersonaggio.setEnabled(true);
            }
        };

        PanelPersonaggio1.addMouseListener(selezioneListener);
        PanelPersonaggio2.addMouseListener(selezioneListener);
        PanelPersonaggio3.addMouseListener(selezioneListener);

        add(PanelScegliPersonaggio);
    }

    private JLabel creaLabel(String path, int w, int h) {
        ImageIcon icon = new ImageIcon(getClass().getResource(path));
        Image img = icon.getImage().getScaledInstance(w, h, Image.SCALE_SMOOTH);
        return new JLabel(new ImageIcon(img));
    }

    private void evidenziaSelezione() {
        PanelPersonaggio1.setBorder(null);
        PanelPersonaggio2.setBorder(null);
        PanelPersonaggio3.setBorder(null);

        if (selezionato != null) {
            selezionato.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PanelInizioPartita = new javax.swing.JPanel();
        txtOggettoPerso = new javax.swing.JLabel();
        labelPersonaggioScelto = new javax.swing.JLabel();
        PanelScegliPersonaggio = new javax.swing.JPanel();
        PanelPersonaggio2 = new javax.swing.JPanel();
        PanelPersonaggio3 = new javax.swing.JPanel();
        BottoneSceltaPersonaggio = new javax.swing.JButton();
        PanelPersonaggio1 = new javax.swing.JPanel();

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/secondoPersonaggio.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/TerzoPersonaggioGDR.png"))); // NOI18N

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/PersonaggioGDR.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtOggettoPerso.setText("perdiOggetto");

        javax.swing.GroupLayout PanelInizioPartitaLayout = new javax.swing.GroupLayout(PanelInizioPartita);
        PanelInizioPartita.setLayout(PanelInizioPartitaLayout);
        PanelInizioPartitaLayout.setHorizontalGroup(
            PanelInizioPartitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInizioPartitaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelInizioPartitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelInizioPartitaLayout.createSequentialGroup()
                        .addComponent(labelPersonaggioScelto)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInizioPartitaLayout.createSequentialGroup()
                        .addGap(0, 288, Short.MAX_VALUE)
                        .addComponent(txtOggettoPerso, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32))))
        );
        PanelInizioPartitaLayout.setVerticalGroup(
            PanelInizioPartitaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInizioPartitaLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(txtOggettoPerso)
                .addGap(149, 149, 149)
                .addComponent(labelPersonaggioScelto)
                .addContainerGap(255, Short.MAX_VALUE))
        );

        PanelScegliPersonaggio.setBackground(new java.awt.Color(255, 255, 204));
        PanelScegliPersonaggio.setLayout(null);

        javax.swing.GroupLayout PanelPersonaggio2Layout = new javax.swing.GroupLayout(PanelPersonaggio2);
        PanelPersonaggio2.setLayout(PanelPersonaggio2Layout);
        PanelPersonaggio2Layout.setHorizontalGroup(
            PanelPersonaggio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        PanelPersonaggio2Layout.setVerticalGroup(
            PanelPersonaggio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PanelScegliPersonaggio.add(PanelPersonaggio2);
        PanelPersonaggio2.setBounds(230, 90, 160, 200);

        javax.swing.GroupLayout PanelPersonaggio3Layout = new javax.swing.GroupLayout(PanelPersonaggio3);
        PanelPersonaggio3.setLayout(PanelPersonaggio3Layout);
        PanelPersonaggio3Layout.setHorizontalGroup(
            PanelPersonaggio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        PanelPersonaggio3Layout.setVerticalGroup(
            PanelPersonaggio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PanelScegliPersonaggio.add(PanelPersonaggio3);
        PanelPersonaggio3.setBounds(463, 90, 140, 200);

        BottoneSceltaPersonaggio.setText("Scegli");
        BottoneSceltaPersonaggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneSceltaPersonaggioActionPerformed(evt);
            }
        });
        PanelScegliPersonaggio.add(BottoneSceltaPersonaggio);
        BottoneSceltaPersonaggio.setBounds(250, 370, 119, 30);

        javax.swing.GroupLayout PanelPersonaggio1Layout = new javax.swing.GroupLayout(PanelPersonaggio1);
        PanelPersonaggio1.setLayout(PanelPersonaggio1Layout);
        PanelPersonaggio1Layout.setHorizontalGroup(
            PanelPersonaggio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        PanelPersonaggio1Layout.setVerticalGroup(
            PanelPersonaggio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PanelScegliPersonaggio.add(PanelPersonaggio1);
        PanelPersonaggio1.setBounds(20, 90, 160, 200);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelScegliPersonaggio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelInizioPartita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelScegliPersonaggio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(PanelInizioPartita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneSceltaPersonaggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneSceltaPersonaggioActionPerformed
        PanelScegliPersonaggio.setVisible(false);
        PanelInizioPartita.setVisible(true);

        ImageIcon icon = new ImageIcon(getClass().getResource(player));
        Image img = icon.getImage().getScaledInstance(120, 150, Image.SCALE_SMOOTH);
        labelPersonaggioScelto.setIcon(new ImageIcon(img));

        labelPersonaggioScelto.setIcon(new ImageIcon(img));
        nemico.oggettoPerso(txtOggettoPerso);
    }//GEN-LAST:event_BottoneSceltaPersonaggioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new Grafica().setVisible(true));
    
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottoneSceltaPersonaggio;
    private javax.swing.JPanel PanelInizioPartita;
    private javax.swing.JPanel PanelPersonaggio1;
    private javax.swing.JPanel PanelPersonaggio2;
    private javax.swing.JPanel PanelPersonaggio3;
    private javax.swing.JPanel PanelScegliPersonaggio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelPersonaggioScelto;
    private javax.swing.JLabel txtOggettoPerso;
    // End of variables declaration//GEN-END:variables
}
