/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package progettogdr;

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author arcaleni.daniele2
 */
public class Grafica extends javax.swing.JFrame {
    private JPanel selezionato = null;

    /**
     * Creates new form Grafica
     */
    public Grafica() {
        setTitle("Selezione Personaggio");
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setSize(640, 480);
        setLocationRelativeTo(null);

        PanelScegliPersonaggio = new JPanel(null);
        PanelScegliPersonaggio.setBackground(new Color(255, 255, 204));

        // PANEL 1: immagine ridimensionata
        PanelPersonaggio1 = new JPanel(new BorderLayout());
        JLabel label1 = new JLabel() {
            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                ImageIcon icon = new ImageIcon(getClass().getResource("/progettogdr/PersonaggioGDR.png"));
                int imgWidth = (int)(getWidth() * 0.6);
                int imgHeight = (int)(getHeight() * 0.6);
                Image img = icon.getImage().getScaledInstance(imgWidth, imgHeight, Image.SCALE_SMOOTH);
                int x = (getWidth() - imgWidth) / 2;
                int y = (getHeight() - imgHeight) / 2;
                g.drawImage(img, x, y, imgWidth, imgHeight, this);
            }
        };
        PanelPersonaggio1.add(label1, BorderLayout.CENTER);
        PanelPersonaggio1.setBounds(25, 90, 150, 200);
        PanelScegliPersonaggio.add(PanelPersonaggio1);

        // PANEL 2 e 3 come box colorati
        PanelPersonaggio2 = new JPanel();
        PanelPersonaggio2.setBackground(Color.BLACK);
        PanelPersonaggio2.setBounds(230, 90, 160, 200);
        PanelScegliPersonaggio.add(PanelPersonaggio2);

        PanelPersonaggio3 = new JPanel();
        PanelPersonaggio3.setBackground(Color.GRAY);
        PanelPersonaggio3.setBounds(463, 90, 140, 200);
        PanelScegliPersonaggio.add(PanelPersonaggio3);
    
        // Bottone Gioca (inizialmente disabilitato)
        BottoneSceltaPersonaggio = new JButton("Gioca");
        BottoneSceltaPersonaggio.setBounds(250, 340, 119, 23);
        BottoneSceltaPersonaggio.setEnabled(false);
        BottoneSceltaPersonaggio.addActionListener(e -> {

        });
                PanelScegliPersonaggio.add(BottoneSceltaPersonaggio);
        MouseAdapter selezioneListener = new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                selezionato = (JPanel)e.getSource();
                evidenziaSelezione();
                BottoneSceltaPersonaggio.setEnabled(true);
            }
        };

        PanelPersonaggio1.addMouseListener(selezioneListener);
        PanelPersonaggio2.addMouseListener(selezioneListener);
        PanelPersonaggio3.addMouseListener(selezioneListener);

        add(PanelScegliPersonaggio);
    }      
    private void evidenziaSelezione(){
        // Reset bordi
        PanelPersonaggio1.setBorder(null);
        PanelPersonaggio2.setBorder(null);
        PanelPersonaggio3.setBorder(null);

        // Evidenzia quello selezionato
        if (selezionato != null) {
            selezionato.setBorder(BorderFactory.createLineBorder(Color.RED, 3));
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelScegliPersonaggio = new javax.swing.JPanel();
        PanelPersonaggio2 = new javax.swing.JPanel();
        PanelPersonaggio1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PanelPersonaggio3 = new javax.swing.JPanel();
        BottoneSceltaPersonaggio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelScegliPersonaggio.setBackground(new java.awt.Color(255, 255, 204));
        PanelScegliPersonaggio.setLayout(null);

        PanelPersonaggio2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout PanelPersonaggio2Layout = new javax.swing.GroupLayout(PanelPersonaggio2);
        PanelPersonaggio2.setLayout(PanelPersonaggio2Layout);
        PanelPersonaggio2Layout.setHorizontalGroup(
            PanelPersonaggio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 160, Short.MAX_VALUE)
        );
        PanelPersonaggio2Layout.setVerticalGroup(
            PanelPersonaggio2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PanelScegliPersonaggio.add(PanelPersonaggio2);
        PanelPersonaggio2.setBounds(230, 90, 160, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/progettogdr/PersonaggioGDR.png"))); // NOI18N

        javax.swing.GroupLayout PanelPersonaggio1Layout = new javax.swing.GroupLayout(PanelPersonaggio1);
        PanelPersonaggio1.setLayout(PanelPersonaggio1Layout);
        PanelPersonaggio1Layout.setHorizontalGroup(
            PanelPersonaggio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelPersonaggio1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PanelPersonaggio1Layout.setVerticalGroup(
            PanelPersonaggio1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPersonaggio1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        PanelScegliPersonaggio.add(PanelPersonaggio1);
        PanelPersonaggio1.setBounds(25, 90, 240, 270);

        javax.swing.GroupLayout PanelPersonaggio3Layout = new javax.swing.GroupLayout(PanelPersonaggio3);
        PanelPersonaggio3.setLayout(PanelPersonaggio3Layout);
        PanelPersonaggio3Layout.setHorizontalGroup(
            PanelPersonaggio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );
        PanelPersonaggio3Layout.setVerticalGroup(
            PanelPersonaggio3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );

        PanelScegliPersonaggio.add(PanelPersonaggio3);
        PanelPersonaggio3.setBounds(463, 90, 140, 200);

        BottoneSceltaPersonaggio.setText("Scegli");
        BottoneSceltaPersonaggio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BottoneSceltaPersonaggioActionPerformed(evt);
            }
        });
        PanelScegliPersonaggio.add(BottoneSceltaPersonaggio);
        BottoneSceltaPersonaggio.setBounds(250, 370, 119, 23);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelScegliPersonaggio, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelScegliPersonaggio, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BottoneSceltaPersonaggioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BottoneSceltaPersonaggioActionPerformed
        PanelScegliPersonaggio.setVisible(false);
        BottoneSceltaPersonaggio.setVisible(false);
        PanelPersonaggio1.setVisible(false);
        PanelPersonaggio2.setVisible(false);
        PanelPersonaggio3.setVisible(false);
        
    }//GEN-LAST:event_BottoneSceltaPersonaggioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new Grafica().setVisible(true));
    
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //</editor-fold>

        /* Create and display the form */
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BottoneSceltaPersonaggio;
    private javax.swing.JPanel PanelPersonaggio1;
    private javax.swing.JPanel PanelPersonaggio2;
    private javax.swing.JPanel PanelPersonaggio3;
    private javax.swing.JPanel PanelScegliPersonaggio;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
